version: "3.8"
services:
  backend:
    build: ./backend
    container_name: api_c
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/backend
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

this is a test